--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13 (Ubuntu 16.13-1.pgdg24.04+1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_state_id_fkey;
ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_country_id_fkey;
ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_city_id_fkey;
DROP INDEX IF EXISTS public.postcodes_state_id_idx;
DROP INDEX IF EXISTS public.postcodes_country_id_code_idx;
DROP INDEX IF EXISTS public.postcodes_code_idx;
DROP INDEX IF EXISTS public.postcodes_city_id_idx;
ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_pkey;
DROP TABLE IF EXISTS public.postcodes;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: postcodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.postcodes (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    country_id bigint NOT NULL,
    country_code character(2) NOT NULL,
    state_id bigint,
    state_code character varying(255),
    city_id bigint,
    locality_name character varying(255),
    type character varying(32),
    latitude numeric(10,8),
    longitude numeric(11,8),
    source character varying(64),
    "wikiDataId" character varying(255),
    created_at timestamp without time zone DEFAULT '2014-01-01 12:01:01'::timestamp without time zone NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    flag smallint DEFAULT 1 NOT NULL
);


--
-- Name: TABLE postcodes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.postcodes IS 'Postal codes (issue #1039) - Tier 4: one row per postcode';


--
-- Name: COLUMN postcodes.code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.code IS 'The postal code value (alphanumeric, country-specific format)';


--
-- Name: COLUMN postcodes.locality_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.locality_name IS 'Human-readable place name associated with the postcode';


--
-- Name: COLUMN postcodes.type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.type IS 'Granularity: full | outward | sector | district | area';


--
-- Name: COLUMN postcodes.source; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.source IS 'Originating data source for license/attribution tracking (e.g. openplz, wikidata, census)';


--
-- Name: COLUMN postcodes."wikiDataId"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes."wikiDataId" IS 'Wikidata Q-ID for cross-referencing';


--
-- Name: postcodes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.postcodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.postcodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: postcodes; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.postcodes VALUES (1, '9485', 125, 'LI', 451, '02', NULL, 'Nendeln', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (2, '9486', 125, 'LI', 455, '04', NULL, 'Schaanwald', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (3, '9487', 125, 'LI', 457, '03', NULL, 'Bendern', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (4, '9488', 125, 'LI', 449, '08', NULL, 'Schellenberg', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (5, '9490', 125, 'LI', 452, '11', NULL, 'Vaduz', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (6, '9491', 125, 'LI', 453, '06', NULL, 'Ruggell', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (7, '9492', 125, 'LI', 451, '02', NULL, 'Eschen', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (8, '9493', 125, 'LI', 455, '04', NULL, 'Mauren', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (9, '9494', 125, 'LI', 450, '07', NULL, 'Schaan', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (10, '9495', 125, 'LI', 459, '09', NULL, 'Triesen', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (11, '9496', 125, 'LI', 458, '01', NULL, 'Balzers', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (12, '9497', 125, 'LI', 456, '10', NULL, 'Triesenberg', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (13, '9498', 125, 'LI', 454, '05', NULL, 'Planken', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (14, '98000', 145, 'MC', NULL, NULL, NULL, 'Monaco', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (15, '47890', 192, 'SM', 58, '07', NULL, 'San Marino', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (16, '47891', 192, 'SM', 65, '09', NULL, 'Serravalle', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (17, '47892', 192, 'SM', 59, '01', NULL, 'Acquaviva', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (18, '47893', 192, 'SM', 61, '06', NULL, 'Borgo Maggiore', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (19, '47894', 192, 'SM', 60, '02', NULL, 'Chiesanuova', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (20, '47895', 192, 'SM', 64, '03', NULL, 'Domagnano', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (21, '47896', 192, 'SM', 62, '04', NULL, 'Faetano', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (22, '47897', 192, 'SM', 66, '05', NULL, 'Fiorentino', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (23, '47898', 192, 'SM', 63, '08', NULL, 'Montegiardino', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);
INSERT INTO public.postcodes VALUES (24, '00120', 238, 'VA', NULL, NULL, NULL, 'Citta del Vaticano', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 15:25:45', '2026-04-25 15:25:45', 1);


--
-- Name: postcodes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.postcodes_id_seq', 24, true);


--
-- Name: postcodes postcodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_pkey PRIMARY KEY (id);


--
-- Name: postcodes_city_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_city_id_idx ON public.postcodes USING btree (city_id);


--
-- Name: postcodes_code_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_code_idx ON public.postcodes USING btree (code);


--
-- Name: postcodes_country_id_code_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_country_id_code_idx ON public.postcodes USING btree (country_id, code);


--
-- Name: postcodes_state_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_state_id_idx ON public.postcodes USING btree (state_id);


--
-- Name: postcodes postcodes_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id) ON DELETE SET NULL;


--
-- Name: postcodes postcodes_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id);


--
-- Name: postcodes postcodes_state_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.states(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--


